name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    name: Python tests and checks
    uses: ./.github/workflows/sub_testing.yml

  build-n-publish:
    name: Build and publish Python 🐍 distributions to PyPI 📦
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    needs: test
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.12"
      - name: Build Exegol
        run: pdm build
      - name: Publish distribution 📦 to Test PyPI
        run: pdm publish --no-build --repository https://test.pypi.org/legacy/ --skip-existing
      - name: Publish distribution 📦 to PyPI (prod)
        run: pdm publish --no-build
