name: Nightly build

on:
  push:
    branches:
      - "dev"
    #paths:
    #  - "**.py"

jobs:
  test:
    name: Python tests and checks
    uses: ./.github/workflows/sub_testing.yml

  build-n-publish:
    name: Build and publish Python 🐍 distributions to TestPyPI 📦
    runs-on: ubuntu-latest
    environment: nightly
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    needs: test
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.12"
      - name: Build Exegol
        run: pdm build
      - name: Publish distribution 📦 to Test PyPI
        run: pdm publish --no-build --repository https://test.pypi.org/legacy/ --skip-existing
